### PR TITLE
Leg 264 collection page

### PR DESCRIPTION
**Pull request by Th3Doo**
## Description
Collection view with discover component
- Mobile version implemented
- Eliminated large amounts of whitespace in desktop version
- Modified assetCard.vue to display correctly in mobile view

### CODE REVIEW

**Comment by Dewald928** [comment]
I dunno this page still feels like it's lacking something.

- [ ] Maybe do the icon position more like opensea's. That bit of overlap with the background. 
- [ ] I'm generally not a fan of making a desktop + mobile version. For the simple fact, it leads to a lots of bugs having to change things in 2 places. 
- [ ] Need a better way of displaying that market fee, created etc. info.

**Comment by Th3Doo** [comment]
#Changes
- Moved collection icon to overlap background
- Moved links inline with collection icon
- Moved info inline with description
- Reduced complexity of mobile version (info only)

**Comment by Dewald928** [comment]
I'm still uneasy about this entire page. Maybe we should just play around with dummy data and see what looks better.

**Review by Dewald928 — APPROVED** [review]
We should come back to this once we are wiser in the ways of CSS. But good enough for now

**Pull request merged**
