### PR TITLE
Leg 341 gallery cards same sizes

### PR DESCRIPTION
**Pull request by Th3Doo**
# Description
- Modified flexbox of asset and template cards so they maintain consistent style and sizing

### CODE REVIEW

**Comment by Dewald928** [comment]
This isn't right. Please review. Try to go through all the pages first and see if everything looks okay. This saves a lot of time in the long run
image

**Comment by Th3Doo** [comment]
My local branch doesn't do this

**Comment by Th3Doo** [comment]
The above only happens with assetsCard collections. I couldn't seem to find out how to test assetCards, as clicking the legalcoin collection on the home page uses templates.

**Comment by Th3Doo** [comment]
Fixed it, there was an indentation error on assetCard.vue. Should look as intended now.

**Pull request merged**
